//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.Data_Update_MSoap")]
    public interface Data_Update_MSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 proc_name 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_Data_String", ReplyAction="*")]
        Service.ServiceReference1.Update_Data_StringResponse Update_Data_String(Service.ServiceReference1.Update_Data_StringRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_Data_String", ReplyAction="*")]
        System.Threading.Tasks.Task<Service.ServiceReference1.Update_Data_StringResponse> Update_Data_StringAsync(Service.ServiceReference1.Update_Data_StringRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 Sql_Str 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Execute_Sql", ReplyAction="*")]
        Service.ServiceReference1.Execute_SqlResponse Execute_Sql(Service.ServiceReference1.Execute_SqlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Execute_Sql", ReplyAction="*")]
        System.Threading.Tasks.Task<Service.ServiceReference1.Execute_SqlResponse> Execute_SqlAsync(Service.ServiceReference1.Execute_SqlRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Update_Data_StringRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update_Data_String", Namespace="http://tempuri.org/", Order=0)]
        public Service.ServiceReference1.Update_Data_StringRequestBody Body;
        
        public Update_Data_StringRequest() {
        }
        
        public Update_Data_StringRequest(Service.ServiceReference1.Update_Data_StringRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Update_Data_StringRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string proc_name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string parames;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string split;
        
        public Update_Data_StringRequestBody() {
        }
        
        public Update_Data_StringRequestBody(string proc_name, string parames, string split) {
            this.proc_name = proc_name;
            this.parames = parames;
            this.split = split;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Update_Data_StringResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update_Data_StringResponse", Namespace="http://tempuri.org/", Order=0)]
        public Service.ServiceReference1.Update_Data_StringResponseBody Body;
        
        public Update_Data_StringResponse() {
        }
        
        public Update_Data_StringResponse(Service.ServiceReference1.Update_Data_StringResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Update_Data_StringResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Update_Data_StringResult;
        
        public Update_Data_StringResponseBody() {
        }
        
        public Update_Data_StringResponseBody(string Update_Data_StringResult) {
            this.Update_Data_StringResult = Update_Data_StringResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Execute_SqlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Execute_Sql", Namespace="http://tempuri.org/", Order=0)]
        public Service.ServiceReference1.Execute_SqlRequestBody Body;
        
        public Execute_SqlRequest() {
        }
        
        public Execute_SqlRequest(Service.ServiceReference1.Execute_SqlRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Execute_SqlRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Sql_Str;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string parames;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string split;
        
        public Execute_SqlRequestBody() {
        }
        
        public Execute_SqlRequestBody(string Sql_Str, string parames, string split) {
            this.Sql_Str = Sql_Str;
            this.parames = parames;
            this.split = split;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Execute_SqlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Execute_SqlResponse", Namespace="http://tempuri.org/", Order=0)]
        public Service.ServiceReference1.Execute_SqlResponseBody Body;
        
        public Execute_SqlResponse() {
        }
        
        public Execute_SqlResponse(Service.ServiceReference1.Execute_SqlResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Execute_SqlResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Execute_SqlResult;
        
        public Execute_SqlResponseBody() {
        }
        
        public Execute_SqlResponseBody(string Execute_SqlResult) {
            this.Execute_SqlResult = Execute_SqlResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Data_Update_MSoapChannel : Service.ServiceReference1.Data_Update_MSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Data_Update_MSoapClient : System.ServiceModel.ClientBase<Service.ServiceReference1.Data_Update_MSoap>, Service.ServiceReference1.Data_Update_MSoap {
        
        public Data_Update_MSoapClient() {
        }
        
        public Data_Update_MSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Data_Update_MSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Data_Update_MSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Data_Update_MSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Service.ServiceReference1.Update_Data_StringResponse Service.ServiceReference1.Data_Update_MSoap.Update_Data_String(Service.ServiceReference1.Update_Data_StringRequest request) {
            return base.Channel.Update_Data_String(request);
        }
        
        public string Update_Data_String(string proc_name, string parames, string split) {
            Service.ServiceReference1.Update_Data_StringRequest inValue = new Service.ServiceReference1.Update_Data_StringRequest();
            inValue.Body = new Service.ServiceReference1.Update_Data_StringRequestBody();
            inValue.Body.proc_name = proc_name;
            inValue.Body.parames = parames;
            inValue.Body.split = split;
            Service.ServiceReference1.Update_Data_StringResponse retVal = ((Service.ServiceReference1.Data_Update_MSoap)(this)).Update_Data_String(inValue);
            return retVal.Body.Update_Data_StringResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Service.ServiceReference1.Update_Data_StringResponse> Service.ServiceReference1.Data_Update_MSoap.Update_Data_StringAsync(Service.ServiceReference1.Update_Data_StringRequest request) {
            return base.Channel.Update_Data_StringAsync(request);
        }
        
        public System.Threading.Tasks.Task<Service.ServiceReference1.Update_Data_StringResponse> Update_Data_StringAsync(string proc_name, string parames, string split) {
            Service.ServiceReference1.Update_Data_StringRequest inValue = new Service.ServiceReference1.Update_Data_StringRequest();
            inValue.Body = new Service.ServiceReference1.Update_Data_StringRequestBody();
            inValue.Body.proc_name = proc_name;
            inValue.Body.parames = parames;
            inValue.Body.split = split;
            return ((Service.ServiceReference1.Data_Update_MSoap)(this)).Update_Data_StringAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Service.ServiceReference1.Execute_SqlResponse Service.ServiceReference1.Data_Update_MSoap.Execute_Sql(Service.ServiceReference1.Execute_SqlRequest request) {
            return base.Channel.Execute_Sql(request);
        }
        
        public string Execute_Sql(string Sql_Str, string parames, string split) {
            Service.ServiceReference1.Execute_SqlRequest inValue = new Service.ServiceReference1.Execute_SqlRequest();
            inValue.Body = new Service.ServiceReference1.Execute_SqlRequestBody();
            inValue.Body.Sql_Str = Sql_Str;
            inValue.Body.parames = parames;
            inValue.Body.split = split;
            Service.ServiceReference1.Execute_SqlResponse retVal = ((Service.ServiceReference1.Data_Update_MSoap)(this)).Execute_Sql(inValue);
            return retVal.Body.Execute_SqlResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Service.ServiceReference1.Execute_SqlResponse> Service.ServiceReference1.Data_Update_MSoap.Execute_SqlAsync(Service.ServiceReference1.Execute_SqlRequest request) {
            return base.Channel.Execute_SqlAsync(request);
        }
        
        public System.Threading.Tasks.Task<Service.ServiceReference1.Execute_SqlResponse> Execute_SqlAsync(string Sql_Str, string parames, string split) {
            Service.ServiceReference1.Execute_SqlRequest inValue = new Service.ServiceReference1.Execute_SqlRequest();
            inValue.Body = new Service.ServiceReference1.Execute_SqlRequestBody();
            inValue.Body.Sql_Str = Sql_Str;
            inValue.Body.parames = parames;
            inValue.Body.split = split;
            return ((Service.ServiceReference1.Data_Update_MSoap)(this)).Execute_SqlAsync(inValue);
        }
    }
}
